version: "3"

services:

  runtime-setup:
    image: netty:default
    build:
      context: .
      dockerfile: Dockerfile.centos6

  common: &common
    image: netty:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ..:/code
    working_dir: /code

  build-leak:
    <<: *common
    command: /bin/bash -cl "./mvnw -Pleak clean install -Dio.netty.testsuite.badHost=netty.io"

  build:
    <<: *common
    command: /bin/bash -cl "./mvnw clean install -Dio.netty.testsuite.badHost=netty.io"

  deploy:
    <<: *common
    command: /bin/bash -cl "./mvnw clean deploy -DskipTests=true"

  test-leak:
    <<: *common
    command: /bin/bash -cl "./mvnw -Pleak clean install -Dio.netty.testsuite.badHost=netty.io -Dmaven.wagon.http.pool=false"

  test:
    <<: *common
    command: /bin/bash -cl "./mvnw clean install -Dio.netty.testsuite.badHost=netty.io -Dmaven.wagon.http.pool=false"

  test-boringssl-static:
    <<: *common
    command: /bin/bash -cl "./mvnw -P boringssl clean install -Dio.netty.testsuite.badHost=netty.io -Dxml.skip=true -Dmaven.wagon.http.pool=false"

  shell:
    <<: *common
    entrypoint: /bin/bash
